import i18n from "i18n-js";
import * as Localization from "expo-localization";
i18n.translations = {
  "en": {
    "Login":"Login",
    "CreateAnAccount":"Create an account"
  },
  "es": {
    "JoinGroup": "Unirse al grupo",
    "CreateGroup": "Crear grupo",
    "Group": "Grupo",
    "Likes": "Me gusta",
    "GroupTopPicks": "Mejores selecciones del grupo",
    "YourLikes": "Tus gustos",
    "GenerateCode": "Generar código de unión",
    "GeneratingCode": "Generando código",
    "JoinCode": "Código de unión",
    "Join": "Unirse",
    "NoGroupPicksYetKeepSwiping": "Aún no hay selecciones grupales. ¡Sigue deslizando!",
    "GroupName": "Nombre del grupo",
    "Type": "Tipo",
    "Providers": "Proveedores",
    "Genre": "Género",
    "Rating": "Calificación",
    "Lookslikeyourlastjoincodeexpired": "Parece que su último código para unirse venció.",
    "AudienceScore": "Puntuación de la audiencia",
    "MoreInfo": "Más información",
    "EnterYourScreenName": "Ingresa tu nombre de usuario",
    "BySubmittingYouAgreeToThe": "Al enviar, aceptas las",
    "TermsAndConditions": "Términos y condiciones",
    "SUBMITSCREENNAME": "ENVIAR NOMBRE DE PANTALLA",
    "Pleaseenterascreenname": "Ingrese un nombre de pantalla.",
    "WelcometoFlixPix": "Bienvenido a FlixPix",
    "swipeanydirectiontocontinue": "desliza el dedo en cualquier dirección para continuar",
    "Swiperighttovoteforashow": "Desliza el dedo hacia la derecha para votar por una película.",
    "Swipelefttovoteagainstashow": "Desliza el dedo hacia la izquierda para votar en contra de una película.",
    "Swipedowntopassonashow": "Desliza el dedo hacia abajo para pasar una película.",
    "SwipeuptochooseashowasyourTopPick": "Desliza el dedo hacia arriba para elegir una película como tu mejor opción",
    "Shakeyourphonetoundoyourlastswipe": "Intenta agitar tu teléfono para deshacer",
    "orswipetocontinue": "(o desliza el dedo para continuar)",
    "Taponacardtogetmoreinformation": "Toque una tarjeta para obtener más información.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Dato de trivia de la película: A Toto le pagaron más que a los Munchkins en El mago de Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Los actores de Munchkin recibían $ 50 a la semana, que era un buen salario en ese momento, mientras que el perro ganaba $ 125 a la semana.",
    "Whatarewewatchingtonight": "¿Qué estamos viendo esta noche?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Forme un grupo o únase a él y elimine las molestias de la noche de cine.",
    "Whatareyouwaitingfor": "¿Que estas esperando? ¡Desliza para comenzar!",
    "OtherInfo": "Otra información",
    "RankingExplaination": "Toca el ícono de clasificación para ver las mejores selecciones de tu grupo y tus Me gusta",
    "ShareExplainations": "Toca el ícono de compartir para agregar personas a tu grupo",
    "SwipeToContinue": "(desliza para continuar)",
    "Action": "Acción",
    "Adventure": "Aventura",
    "Animation": "Animación",
    "Comedy": "Comedia",
    "Crime": "Crimen",
    "Documentary": "Documental",
    "Drama": "Drama",
    "Family": "Familia",
    "Fantasy": "Fantasía",
    "History": "Historia",
    "Horror": "Horror",
    "Music": "Música",
    "Mystery": "Misterio",
    "Romance": "Romance",
    "ScienceFiction": "Ciencia ficción",
    "TVMovie": "Película de televisión",
    "Thriller": "Thriller",
    "War": "Guerra",
    "Western": "Occidental",
    "ActionAdventure": "Acción y aventura",
    "Kids": "Niños",
    "News": "Noticias",
    "Reality": "Realidad",
    "SciFiFantasy": "Ciencia ficción y fantasía",
    "Soap": "Jabón",
    "Talk": "Hablar",
    "WarPolitics": "Guerra y política",
    "Liked": "Me gustó",
    "Disliked": "No me gustó",
    "Passed": "Aprobado",
    "TopPick": "Top Pick",
    "OK": "OK",
    "Cancel": "Cancelar",
    "Undolastswipe": "¿Deshacer el último deslizamiento?",
    "Noundoisavaliable": "No se puede deshacer.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "¡Has pasado por todo el contenido de tus filtros actuales!",
    "All out of top picks": "¡Todos fuera de las mejores opciones!",
    "Like what you see": "¿Te gusta lo que ves?",
    "Srtvy": "Desliza el dedo hacia la derecha para votar por esta película. ¡Te avisaremos si coincide!",
    "Not interested": "¿No interesado?",
    "SLIYNIN": "Desliza el dedo hacia la izquierda si no estás interesado en esta película.",
    "NOT INTERESTED": "NO INTERESADO",
    "Is this one of your top pick": "¿Es esta una de tus mejores opciones?",
    "MakeITCountt": "Desliza el dedo hacia arriba si realmente te gusta esta película y quieres mostrarla. Solo tienes 2 por grupo, ¡así que haz que cuente!",
    "PASS": "PASA",
    "Swipedowntopass": "Deslizar hacia abajo pasará esta película.",
    "No opinion": "¿Sin opinión?",
    "enter a group name": "Ingrese un nombre de grupo.",
    "An error occured": "Ocurrió un error.",
    "No enough shows found under current filters": "No se han encontrado suficientes programas en los filtros actuales.",
    "Invalid join code": "Código de unión no válido.",
    "You have already joined this group": "Ya te has unido a este grupo.",
    "JCNV": "El código de unión no es válido.",
    "Leave Group": "¿Salir del grupo?",
    "Network Error": "Error de red.",
    "Load More": "Cargar más",
    "Name": "Nombre",
    "Download the app, and join": "Descarga la aplicación y únete",
    "let's find what to watch": "encontremos qué mirar.",
    "It'sAMatch": "¡ES UN PARTIDO!"
  },
  "ru": {
    "JoinGroup": "Присоединиться к группе",
    "CreateGroup": "Создать группу",
    "Group": "Группа",
    "Likes": "Нравится",
    "GroupTopPicks": "Лучшие предложения группы",
    "YourLikes": "Ваши лайки",
    "GenerateCode": "Создать код присоединения",
    "GeneratingCode": "Генерация кода",
    "JoinCode": "Код регистрации",
    "Join": "Присоединяйтесь",
    "NoGroupPicksYetKeepSwiping": "Групповых выборов пока нет. Продолжайте листать!",
    "GroupName": "Название группы",
    "Type": "Тип",
    "Providers": "Провайдеры",
    "Genre": "Жанр",
    "Rating": "Рейтинг",
    "Lookslikeyourlastjoincodeexpired": "Похоже, срок действия вашего последнего кода присоединения истек.",
    "AudienceScore": "Оценка аудитории",
    "MoreInfo": "Подробнее",
    "EnterYourScreenName": "Введите свой псевдоним",
    "BySubmittingYouAgreeToThe": "Отправляя, вы соглашаетесь с",
    "TermsAndConditions": "Положения и условия",
    "SUBMITSCREENNAME": "ОТПРАВИТЬ НАЗВАНИЕ ЭКРАНА",
    "Pleaseenterascreenname": "Пожалуйста, введите псевдоним.",
    "WelcometoFlixPix": "Добро пожаловать в FlixPix",
    "swipeanydirectiontocontinue": "проведите пальцем в любом направлении, чтобы продолжить",
    "Swiperighttovoteforashow": "Проведите вправо, чтобы проголосовать за фильм.",
    "Swipelefttovoteagainstashow": "Проведите пальцем влево, чтобы проголосовать против фильма.",
    "Swipedowntopassonashow": "Проведите пальцем вниз, чтобы перейти к фильму.",
    "SwipeuptochooseashowasyourTopPick": "Проведите пальцем вверх, чтобы выбрать фильм в качестве лучшего выбора",
    "Shakeyourphonetoundoyourlastswipe": "Чтобы отменить действие, попробуйте встряхнуть телефон",
    "orswipetocontinue": "(или проведите пальцем, чтобы продолжить.)",
    "Taponacardtogetmoreinformation": "Нажмите на карточку, чтобы получить дополнительную информацию.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Факты о фильмах: Тото платили больше, чем Жевунам в «Волшебнике страны Оз»",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Актеры манчкинов получали 50 долларов в неделю - что было неплохим заработком в то время, - в то время как собака зарабатывала 125 долларов в неделю.",
    "Whatarewewatchingtonight": "Что мы смотрим сегодня вечером?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Создайте группу или присоединитесь к ней и избавьтесь от хлопот во время просмотра фильмов.",
    "Whatareyouwaitingfor": "Чего ты ждешь? Проведите пальцем, чтобы начать!",
    "OtherInfo": "Другая информация",
    "RankingExplaination": "Нажмите на значок рейтинга, чтобы увидеть лучшие выборы вашей группы и ваши лайки",
    "ShareExplainations": "Нажмите значок «Поделиться», чтобы добавить людей в свою группу",
    "SwipeToContinue": "(проведите пальцем, чтобы продолжить)",
    "Action": "Действие",
    "Adventure": "Приключение",
    "Animation": "Анимация",
    "Comedy": "Комедия",
    "Crime": "Преступление",
    "Documentary": "Документальный фильм",
    "Drama": "Драма",
    "Family": "Семья",
    "Fantasy": "Фантазия",
    "History": "История",
    "Horror": "Ужас",
    "Music": "Музыка",
    "Mystery": "Тайна",
    "Romance": "Романтика",
    "ScienceFiction": "Научная фантастика",
    "TVMovie": "ТВ-фильм",
    "Thriller": "Триллер",
    "War": "Война",
    "Western": "Западный",
    "ActionAdventure": "Боевики и приключения",
    "Kids": "Дети",
    "News": "Новости",
    "Reality": "Реальность",
    "SciFiFantasy": "Научная фантастика и фэнтези",
    "Soap": "Мыло",
    "Talk": "Обсуждение",
    "WarPolitics": "Война и политика",
    "Liked": "Понравилось",
    "Disliked": "Не понравилось",
    "Passed": "Прошло",
    "TopPick": "Лучший выбор",
    "OK": "ОК",
    "Cancel": "Отменить",
    "Undolastswipe": "Отменить последнее смахивание?",
    "Noundoisavaliable": "Отменить нельзя.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Вы просмотрели весь контент в ваших текущих фильтрах!",
    "All out of top picks": "Все из лучших!",
    "Like what you see": "Нравится то, что вы видите?",
    "Srtvy": "Проведите по экрану вправо, чтобы проголосовать за этот фильм. Мы сообщим вам, если это совпадение!",
    "Not interested": "Не интересует?",
    "SLIYNIN": "Проведите пальцем влево, если этот фильм вас не интересует.",
    "NOT INTERESTED": "НЕ ИНТЕРЕСНО",
    "Is this one of your top pick": "Это один из ваших лучших выборов?",
    "MakeITCountt": "Смахните вверх, если вам действительно нравится этот фильм и вы хотите его показать. У вас есть только 2 на группу, так что учитывайте!",
    "PASS": "ПРОЙТИ",
    "Swipedowntopass": "Проведите пальцем вниз по этому фильму.",
    "No opinion": "Нет мнения?",
    "enter a group name": "Пожалуйста, введите название группы.",
    "An error occured": "Произошла ошибка.",
    "No enough shows found under current filters": "Под текущими фильтрами не найдено достаточно шоу.",
    "Invalid join code": "Недействительный код присоединения.",
    "You have already joined this group": "Вы уже присоединились к этой группе.",
    "JCNV": "Код присоединения недействителен.",
    "Leave Group": "Покинуть группу?",
    "Network Error": "Ошибка сети.",
    "Load More": "Загрузить еще",
    "Name": "Имя",
    "Download the app, and join": "Загрузите приложение и присоединяйтесь",
    "let's find what to watch": "давай найдем, что смотреть.",
    "It'sAMatch": "ЭТО МАТЧ!"
  },
  "ja": {
    "JoinGroup": "グループに参加",
    "CreateGroup": "グループを作成",
    "Group": "グループ",
    "Likes": "いいね",
    "GroupTopPicks": "グループのトップピック",
    "YourLikes": "あなたのいいね",
    "GenerateCode": "参加コードを生成",
    "GeneratingCode": "コードを生成",
    "JoinCode": "コードに参加",
    "Join": "参加",
    "NoGroupPicksYetKeepSwiping": "いいえグループはまだ選んでいます。スワイプを続けてください！",
    "GroupName": "グループ名",
    "Type": "タイプ",
    "Providers": "プロバイダー",
    "Genre": "ジャンル",
    "Rating": "評価",
    "Lookslikeyourlastjoincodeexpired": "最後の参加コードの有効期限が切れているようです。",
    "AudienceScore": "オーディエンススコア",
    "MoreInfo": "詳細情報",
    "EnterYourScreenName": "入力してくださいスクリーン名",
    "BySubmittingYouAgreeToThe": "送信することにより、",
    "TermsAndConditions": "利用規約",
    "SUBMITSCREENNAME": "スクリーン名を送信",
    "Pleaseenterascreenname": "スクリーン名を入力してください。",
    "WelcometoFlixPix": " FlixPixへようこそ",
    "swipeanydirectiontocontinue": "任意の方向にスワイプして続行します",
    "Swiperighttovoteforashow": "右にスワイプして映画に投票します。",
    "Swipelefttovoteagainstashow": "左にスワイプして映画に反対票を投じます。",
    "Swipedowntopassonashow": "下にスワイプして映画を渡します。",
    "SwipeuptochooseashowasyourTopPick": "上にスワイプしてトップピックとして映画を選択します",
    "Shakeyourphonetoundoyourlastswipe": "電話を振ってみます元に戻す",
    "orswipetocontinue": "（またはスワイプして続行します。）",
    "Taponacardtogetmoreinformation": "カードをタップして詳細情報を取得します。",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "映画の雑学クイズ：トトはオズの魔法使いのマンチキンよりも多く支払われました",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "マンチキンの俳優が受け取った犬が週に125ドルを稼いでいる間、週に50ドル（当時は良い賃金でした）。",
    "Whatarewewatchingtonight": "今夜は何を見ていますか？",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "グループを作るか、グループに参加して、映画の夜の煩わしさを取り除きます。;; ;何を待っていますか？スワイプして開始！",
    "Whatareyouwaitingfor": "その他の情報",
    "OtherInfo": "ランキングアイコンをタップしてグループのおすすめやいいねを表示",
    "RankingExplaination": "共有アイコンをタップしてグループにユーザーを追加",
    "ShareExplainations": "（スワイプして続行）;; ;アクション",
    "SwipeToContinue": "アドベンチャー",
    "Action": "アニメーション",
    "Adventure": "コメディ",
    "Animation": "犯罪",
    "Comedy": "ドキュメンタリー",
    "Crime": "ドラマ",
    "Documentary": "家族",
    "Drama": "ファンタジー",
    "Family": "歴史",
    "Fantasy": "ホラー",
    "History": "音楽",
    "Horror": "ミステリー",
    "Music": "ロマンス",
    "Mystery": "サイエンスフィクション",
    "Romance": " TV映画",
    "ScienceFiction": "スリラー",
    "TVMovie": "戦争",
    "Thriller": "西洋",
    "War": "アクション＆アドベンチャー",
    "Western": "キッズ",
    "ActionAdventure": "ニュース",
    "Kids": "リアリティ",
    "News": "サイエンスフィクション＆ファンタジー",
    "Reality": "石鹸",
    "SciFiFantasy": "トーク",
    "Soap": "戦争と政治",
    "Talk": "好き",
    "WarPolitics": "嫌い",
    "Liked": "合格",
    "Disliked": "トップピック",
    "Passed": " OK ",
    "TopPick": "キャンセル",
    "OK": "最後のスワイプを元に戻す？;; ;元に戻すことはできません。",
    "Cancel": "現在のフィルターのすべてのコンテンツをスワイプしました！",
    "Undolastswipe": "すべてのトップピックから！",
    "Noundoisavaliable": "表示されているものと同じですか？",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "右にスワイプしてこの映画に投票してください。一致するかどうかをお知らせします！",
    "All out of top picks": "興味がない？",
    "Like what you see": "この映画に興味がない場合は左にスワイプします。",
    "Srtvy": "興味がない",
    "Not interested": "これはあなたの一番のおすすめですか？;; ;この映画が本当に好きで、見せたい場合は上にスワイプしてください。グループごとに2つしかないので、カウントしてください！",
    "SLIYNIN": "合格",
    "NOT INTERESTED": "下にスワイプするとこのフィルムが渡されます。",
    "Is this one of your top pick": "意見はありませんか？",
    "MakeITCountt": "グループ名を入力してください。",
    "PASS": "エラーが発生しました。; ;;現在のフィルターで十分な表示が見つかりません。",
    "Swipedowntopass": "無効な参加コード。",
    "No opinion": "すでにこのグループに参加しています。",
    "enter a group name": "参加コードが無効です。",
    "An error occured": "グループを脱退しますか？",
    "No enough shows found under current filters": "ネットワークエラー。",
    "Invalid join code": "もっと読み込む",
    "You have already joined this group": "名前",
    "JCNV": "アプリをダウンロードして参加",
    "Leave Group": "見たいものを見つけましょう。",
    "Network Error": "それはマッチです！",
    "Load More": "もっと読み込む",
    "Name": "名前",
    "Download the app, and join": "アプリをダウンロードして参加",
    "let's find what to watch": "見たいものを見つけましょう。",
    "It'sAMatch": "それはマッチです！"
  },
  "it": {
    "JoinGroup": "Unisciti al gruppo",
    "CreateGroup": "Crea gruppo",
    "Group": "Gruppo",
    "Likes": "Mi piace",
    "GroupTopPicks": "Scelte migliori del gruppo",
    "YourLikes": "I tuoi Mi piace",
    "GenerateCode": "Genera codice di iscrizione",
    "GeneratingCode": "Generazione del codice",
    "JoinCode": "Unisciti al codice",
    "Join": "Partecipa",
    "NoGroupPicksYetKeepSwiping": "Nessuna selezione di gruppo ancora. Continua a scorrere!",
    "GroupName": "Nome del gruppo",
    "Type": "Tipo",
    "Providers": "Fornitori",
    "Genre": "Genere",
    "Rating": "Valutazione",
    "Lookslikeyourlastjoincodeexpired": "Sembra che il tuo ultimo codice di iscrizione sia scaduto.",
    "AudienceScore": "Punteggio del pubblico",
    "MoreInfo": "Maggiori informazioni",
    "EnterYourScreenName": "Inserisci il tuo nickname",
    "BySubmittingYouAgreeToThe": "Inviando, accetti il",
    "TermsAndConditions": "Termini e condizioni",
    "SUBMITSCREENNAME": "INVIA NOME SCHERMO",
    "Pleaseenterascreenname": "Per favore inserisci uno screen name.",
    "WelcometoFlixPix": "Benvenuto in FlixPix",
    "swipeanydirectiontocontinue": "scorri in qualsiasi direzione per continuare",
    "Swiperighttovoteforashow": "Scorri verso destra per votare un film.",
    "Swipelefttovoteagainstashow": "Scorri verso sinistra per votare contro un film.",
    "Swipedowntopassonashow": "Scorri verso il basso per passare un film.",
    "SwipeuptochooseashowasyourTopPick": "Scorri verso l'alto per scegliere un film come Migliore scelta",
    "Shakeyourphonetoundoyourlastswipe": "Prova a scuotere il telefono per annullare",
    "orswipetocontinue": "(o scorri per continuare.)",
    "Taponacardtogetmoreinformation": "Tocca una scheda per ottenere maggiori informazioni.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Curiosità sul film: Toto è stato pagato più dei Munchkin in Il mago di Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Gli attori di Munchkin ricevevano $ 50 a settimana, che all'epoca era un buon salario, mentre il cane guadagnava $ 125 a settimana.",
    "Whatarewewatchingtonight": "Cosa guardiamo stasera?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Crea o unisciti a un gruppo e elimina i problemi della serata al cinema.",
    "Whatareyouwaitingfor": "Che cosa state aspettando? Scorri per iniziare!",
    "OtherInfo": "Altre informazioni",
    "RankingExplaination": "Tocca l'icona della classifica per vedere le scelte migliori del tuo gruppo e i tuoi Mi piace",
    "ShareExplainations": "Tocca l'icona di condivisione per aggiungere persone al tuo gruppo",
    "SwipeToContinue": "(scorri per continuare)",
    "Action": "Azione",
    "Adventure": "Avventura",
    "Animation": "Animazione",
    "Comedy": "Commedia",
    "Crime": "Crimine",
    "Documentary": "Documentario",
    "Drama": "Dramma",
    "Family": "Famiglia",
    "Fantasy": "Fantasy",
    "History": "Storia",
    "Horror": "Orrore",
    "Music": "Musica",
    "Mystery": "Mistero",
    "Romance": "Romance",
    "ScienceFiction": "Fantascienza",
    "TVMovie": "TV Movie",
    "Thriller": "Thriller",
    "War": "Guerra",
    "Western": "Western",
    "ActionAdventure": "Azione e avventura",
    "Kids": "Bambini",
    "News": "Notizie",
    "Reality": "Realtà",
    "SciFiFantasy": "Fantascienza e fantasy",
    "Soap": "Sapone",
    "Talk": "Parla",
    "WarPolitics": "Guerra e politica",
    "Liked": "Piaciuto",
    "Disliked": "Non mi è piaciuto",
    "Passed": "Superato",
    "TopPick": "Scelta migliore",
    "OK": "OK",
    "Cancel": "Annulla",
    "Undolastswipe": "Annullare l'ultimo passaggio?",
    "Noundoisavaliable": "Nessun annullamento è disponibile.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Hai fatto scorrere tutto il contenuto nei filtri attuali!",
    "All out of top picks": "Tutti fuori dalle scelte migliori!",
    "Like what you see": "Ti piace quello che vedi?",
    "Srtvy": "Scorri verso destra per votare questo film. Ti faremo sapere se è una partita!",
    "Not interested": "Non interessato?",
    "SLIYNIN": "Scorri verso sinistra se non sei interessato a questo film.",
    "NOT INTERESTED": "NON INTERESSATO",
    "Is this one of your top pick": "Questa è una delle tue scelte migliori?",
    "MakeITCountt": "Scorri verso l'alto se ti piace davvero questo film e vuoi mostrarlo. Ne hai solo 2 per gruppo, quindi fallo contare!",
    "PASS": "PASS",
    "Swipedowntopass": "Lo scorrimento verso il basso passerà a questo film.",
    "No opinion": "Nessuna opinione?",
    "enter a group name": "Si prega di inserire un nome di gruppo.",
    "An error occured": "Si è verificato un errore.",
    "No enough shows found under current filters": "Non sono stati trovati abbastanza spettacoli con i filtri attuali.",
    "Invalid join code": "Codice di partecipazione non valido.",
    "You have already joined this group": "Ti sei già iscritto a questo gruppo.",
    "JCNV": "Codice di partecipazione non valido.",
    "Leave Group": "Uscire dal gruppo?",
    "Network Error": "Errore di rete.",
    "Load More": "Carica altro",
    "Name": "Nome",
    "Download the app, and join": "Scarica l'app e unisciti a",
    "let's find what to watch": "troviamo cosa guardare.",
    "It'sAMatch": "È UNA PARTITA!"
  },
  "fr": {
    "JoinGroup": "Rejoindre le groupe",
    "CreateGroup": "Créer un groupe",
    "Group": "Groupe",
    "Likes": "Aime",
    "GroupTopPicks": "Top des sélections de groupe",
    "YourLikes": "Vos goûts",
    "GenerateCode": "Générer un code de jointure",
    "GeneratingCode": "Générer du code",
    "JoinCode": "Code d'inscription",
    "Join": "Rejoindre",
    "NoGroupPicksYetKeepSwiping": "Aucun choix de groupe pour le moment. Continuez à glisser!",
    "GroupName": "Nom du groupe",
    "Type": "Type",
    "Providers": "Fournisseurs",
    "Genre": "Genre",
    "Rating": "Évaluation",
    "Lookslikeyourlastjoincodeexpired": "Il semble que votre dernier code de participation a expiré.",
    "AudienceScore": "Score d'audience",
    "MoreInfo": "Plus d'infos",
    "EnterYourScreenName": "Entrez votre pseudo",
    "BySubmittingYouAgreeToThe": "En soumettant, vous acceptez le",
    "TermsAndConditions": "Termes et conditions",
    "SUBMITSCREENNAME": "SOUMETTRE LE NOM DE L'ÉCRAN",
    "Pleaseenterascreenname": "Veuillez saisir un nom d'écran.",
    "WelcometoFlixPix": "Bienvenue à FlixPix",
    "swipeanydirectiontocontinue": "balayez n'importe quelle direction pour continuer",
    "Swiperighttovoteforashow": "Balayez vers la droite pour voter pour un film.",
    "Swipelefttovoteagainstashow": "Faites glisser votre doigt vers la gauche pour voter contre un film.",
    "Swipedowntopassonashow": "Faites glisser votre doigt vers le bas pour passer un film.",
    "SwipeuptochooseashowasyourTopPick": "Faites glisser votre doigt vers le haut pour choisir un film comme premier choix",
    "Shakeyourphonetoundoyourlastswipe": "Essayez de secouer votre téléphone pour annuler",
    "orswipetocontinue": "(ou faites glisser pour continuer.)",
    "Taponacardtogetmoreinformation": "Appuyez sur une carte pour obtenir plus d'informations.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "Movie Trivia Fact: Toto a été payé plus que les Munchkins dans Le Magicien d'Oz",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "Les acteurs de Munchkin recevaient 50 $ par semaine - ce qui était un bon salaire à l'époque - tandis que le chien gagnait 125 $ par semaine.",
    "Whatarewewatchingtonight": "Que regardons-nous ce soir?",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "Créez ou rejoignez un groupe et évitez les tracas de la soirée cinéma.",
    "Whatareyouwaitingfor": "Qu'est-ce que tu attends? Faites glisser pour commencer!",
    "OtherInfo": "Autres informations",
    "RankingExplaination": "Appuyez sur l'icône de classement pour voir les meilleurs choix de votre groupe et vos goûts",
    "ShareExplainations": "Appuyez sur l'icône de partage pour ajouter des personnes à votre groupe",
    "SwipeToContinue": "(balayez pour continuer)",
    "Action": "Action",
    "Adventure": "Aventure",
    "Animation": "Animation",
    "Comedy": "Comédie",
    "Crime": "Crime",
    "Documentary": "Documentaire",
    "Drama": "Drame",
    "Family": "Famille",
    "Fantasy": "Fantaisie",
    "History": "Histoire",
    "Horror": "Horreur",
    "Music": "Musique",
    "Mystery": "Mystère",
    "Romance": "Romance",
    "ScienceFiction": "Science Fiction",
    "TVMovie": "Film télévisé",
    "Thriller": "Thriller",
    "War": "Guerre",
    "Western": "Western",
    "ActionAdventure": "Action et aventure",
    "Kids": "Enfants",
    "News": "Actualités",
    "Reality": "Réalité",
    "SciFiFantasy": "Science-fiction et fantastique",
    "Soap": "Savon",
    "Talk": "Parler",
    "WarPolitics": "Guerre et politique",
    "Liked": "Aimé",
    "Disliked": "N'a pas aimé",
    "Passed": "Adopté",
    "TopPick": "Meilleur choix",
    "OK": "OK",
    "Cancel": "Annuler",
    "Undolastswipe": "Annuler le dernier balayage?",
    "Noundoisavaliable": "Aucune annulation n'est disponible.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "Vous avez parcouru tout le contenu de vos filtres actuels!",
    "All out of top picks": "Tous parmi les meilleurs choix!",
    "Like what you see": "Aimez ce que vous voyez?",
    "Srtvy": "Balayez vers la droite pour voter pour ce film. Nous vous ferons savoir si c'est un match!",
    "Not interested": "Pas intéressé?",
    "SLIYNIN": "Balayez vers la gauche si vous n'êtes pas intéressé par ce film.",
    "NOT INTERESTED": "PAS INTÉRESSÉ",
    "Is this one of your top pick": "Est-ce l'un de vos meilleurs choix?",
    "MakeITCountt": "Balayez vers le haut si vous aimez vraiment ce film et que vous souhaitez le montrer. Vous n'en avez que 2 par groupe, alors faites en sorte que ça compte!",
    "PASS": "PASS",
    "Swipedowntopass": "Glisser vers le bas passera sur ce film.",
    "No opinion": "Pas d'opinion?",
    "enter a group name": "Veuillez saisir un nom de groupe.",
    "An error occured": "Une erreur s'est produite.",
    "No enough shows found under current filters": "Pas assez d'émissions trouvées sous les filtres actuels.",
    "Invalid join code": "Code de participation non valide.",
    "You have already joined this group": "Vous avez déjà rejoint ce groupe.",
    "JCNV": "Code d'inscription non valide.",
    "Leave Group": "Quitter le groupe?",
    "Network Error": "Erreur réseau.",
    "Load More": "Charger plus",
    "Name": "Nom",
    "Download the app, and join": "Téléchargez l'application et rejoignez",
    "let's find what to watch": "trouvons quoi regarder.",
    "It'sAMatch": "C'EST UN MATCH!"
  },
  "ar": {
    "JoinGroup": "الانضمام إلى المجموعة",
    "CreateGroup": "إنشاء مجموعة",
    "Group": "المجموعة",
    "Likes": "الإعجابات",
    "GroupTopPicks": "أفضل المجموعات",
    "YourLikes": "الإعجابات الخاصة بك",
    "GenerateCode": "إنشاء رمز الانضمام",
    "GeneratingCode": "توليد كود",
    "JoinCode": "الانضمام إلى Code",
    "Join": "انضمام",
    "NoGroupPicksYetKeepSwiping": "لا مجموعة يختار بعد. استمر في الضرب!",
    "GroupName": "اسم المجموعة",
    "Type": "اكتب",
    "Providers": "الموفرون",
    "Genre": "النوع",
    "Rating": "التقييم",
    "Lookslikeyourlastjoincodeexpired": "يبدو أن رمز الانضمام الأخير الخاص بك قد انتهت صلاحيته.",
    "AudienceScore": "نقاط الجمهور",
    "MoreInfo": "مزيد من المعلومات",
    "EnterYourScreenName": "أدخل اسم شاشتك",
    "BySubmittingYouAgreeToThe": "من خلال الإرسال ، فإنك توافق على",
    "TermsAndConditions": "الشروط والأحكام",
    "SUBMITSCREENNAME": "إرسال اسم الشاشة",
    "Pleaseenterascreenname": "الرجاء إدخال اسم الشاشة.",
    "WelcometoFlixPix": "مرحبًا بك في FlixPix",
    "swipeanydirectiontocontinue": "انتقد أي اتجاه للمتابعة",
    "Swiperighttovoteforashow": "انتقد الحق في التصويت لفيلم.",
    "Swipelefttovoteagainstashow": "اسحب لليسار للتصويت ضد فيلم.",
    "Swipedowntopassonashow": "اسحب لأسفل لتمرير فيلم.",
    "SwipeuptochooseashowasyourTopPick": "مرر سريعًا لاختيار فيلم باعتباره أفضل اختيار لك",
    "Shakeyourphonetoundoyourlastswipe": "حاول هز هاتفك للتراجع",
    "orswipetocontinue": "(أو اسحب للمتابعة.)",
    "Taponacardtogetmoreinformation": "اضغط على بطاقة للحصول على مزيد من المعلومات.",
    "MovieTriviaFactTotowaspaidmorethantheMunchkinsinTheWizardofOz": "حقيقة تريفيا في الفيلم: حصل توتو على أجر أكثر من مانشكينز في ساحر أوز",
    "TheMunchkinactorsreceived50aweekwhichwasagoodwageatthetimewhilethedogearned125aweek": "حصل ممثلو Munchkin على 50 دولارًا في الأسبوع - وهو أجر جيد في ذلك الوقت - بينما كان الكلب يكسب 125 دولارًا في الأسبوع.",
    "Whatarewewatchingtonight": "ماذا نشاهد الليلة؟",
    "Makeorjoinagroupandtakethehassleoutofmovienight": "أنشئ مجموعة أو انضم إليها ، وتخلص من متاعب ليلة مشاهدة الأفلام.",
    "Whatareyouwaitingfor": "ماذا تنتظر؟ انتقد لتبدأ!",
    "OtherInfo": "معلومات أخرى",
    "RankingExplaination": "اضغط على أيقونة الترتيب لترى أفضل اختيارات مجموعتك وما يعجبك",
    "ShareExplainations": "اضغط على أيقونة المشاركة لإضافة أشخاص إلى مجموعتك",
    "SwipeToContinue": "(اسحب للمتابعة)",
    "Action": "عمل",
    "Adventure": "المغامرة",
    "Animation": "الرسوم المتحركة",
    "Comedy": "كوميديا",
    "Crime": "جريمة",
    "Documentary": "وثائقي",
    "Drama": "دراما",
    "Family": "العائلة",
    "Fantasy": "الخيال",
    "History": "التاريخ",
    "Horror": "رعب",
    "Music": "موسيقى",
    "Mystery": "لغز",
    "Romance": "الرومانسية",
    "ScienceFiction": "خيال علمي",
    "TVMovie": "فيلم تلفزيوني",
    "Thriller": "إثارة",
    "War": "حرب",
    "Western": "الغربي",
    "ActionAdventure": "أكشن ومغامرة",
    "Kids": "الاطفال",
    "News": "أخبار",
    "Reality": "الواقع",
    "SciFiFantasy": "خيال علمي وفانتازيا",
    "Soap": "صابون",
    "Talk": "نقاش",
    "WarPolitics": "الحرب والسياسة",
    "Liked": "أعجبني",
    "Disliked": "لم يعجبه",
    "Passed": "ناجح",
    "TopPick": "أفضل اختيار",
    "OK": "موافق",
    "Cancel": "إلغاء",
    "Undolastswipe": "التراجع عن التمرير الأخير؟",
    "Noundoisavaliable": "لا يوجد تراجع متاح.",
    "Youveswipedthroughallthecontentinyourcurrentfilters": "لقد قمت بالتمرير عبر كل المحتوى الموجود في عوامل التصفية الحالية!",
    "All out of top picks": "كل من بين أفضل الاختيارات!",
    "Like what you see": "مثل ما ترى؟",
    "Srtvy": "انتقد الحق في التصويت لهذا الفيلم. سنخبرك إذا كانت مباراة!",
    "Not interested": "لست مهتمًا؟",
    "SLIYNIN": "اسحب لليسار إذا لم تكن مهتمًا بهذا الفيلم.",
    "NOT INTERESTED": "غير مهتم",
    "Is this one of your top pick": "هل هذا واحد من أفضل اختياراتك؟",
    "MakeITCountt": "اسحب لأعلى إذا أعجبك هذا الفيلم حقًا وترغب في عرضه. لديك 2 فقط لكل مجموعة ، لذا اجعلها مهمة!",
    "PASS": "اجتياز",
    "Swipedowntopass": "الضرب لأسفل سيمر على هذا الفيلم.",
    "No opinion": "لا رأي؟",
    "enter a group name": "الرجاء إدخال اسم المجموعة.",
    "An error occured": "حدث خطأ.",
    "No enough shows found under current filters": "لم يتم العثور على عروض كافية ضمن المرشحات الحالية.",
    "Invalid join code": "رمز الانضمام غير صالح.",
    "You have already joined this group": "لقد انضممت بالفعل إلى هذه المجموعة.",
    "JCNV": "رمز الانضمام غير صالح.",
    "Leave Group": "غادر المجموعة؟",
    "Network Error": "خطأ في الشبكة.",
    "Load More": "تحميل المزيد",
    "Name": "الاسم",
    "Download the app, and join": "قم بتنزيل التطبيق وانضم إلى",
    "let's find what to watch": "دعونا نجد ما نشاهده.",
    "It'sAMatch": "انها مباراة!"
  }
};

//   "ar": "Arabic",
//   "nl": "Dutch",
//   "en": "English",
//   "fr": "French",
//   "el": "Greek",
//   "hi": "Hindi",
//   "it": "Italian",
//   "ja": "Japanese",
//   "la": "Latin",
//   "ru": "Russian",
//   "es": "Spanish"
//de german
//sv sweetish

// sv: {
//     JoinGroup: "",
//     CreateGroup: "",
//     Group: "",
//     Likes: "",
//     GroupTopPicks: "",
//     YourLikes: "",
//     GenerateCode: "",
//     GeneratingCode: "",
//     JoinCode: "",
//   },
i18n.locale = Localization.locale;
i18n.fallbacks = true;
// {i18n.t(" ")}



